/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly 2.0.5.Final - 1.3.11.Final
 * Generated at: 2017-01-07 09:46:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t    <title>Timeline Nobel Prizes</title>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- boostrap css -->\r\n");
      out.write("\t    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    <link href=\"http://mdbootstrap.com/mdbcdn/mdb.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    <!-- google icon -->\r\n");
      out.write("\t    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\" />\r\n");
      out.write("\t    \r\n");
      out.write("\t\t<!-- page css  -->\r\n");
      out.write("\t    <link href=\"Style/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<!-- form css  -->\r\n");
      out.write("\t    <link href=\"Style/form.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    \r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"wide\" style=\"background-image: url(Images/background_presentation.jpg)\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"position: absolute; top: 0; left: 0; width: 150px; text-align:right;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t  \r\n");
      out.write("\t            <div class=\"col-xs-5 line\"><hr></div>\r\n");
      out.write("\t            <div class=\"col-xs-2 logo\">Timeline Nobel Prizes</div>\r\n");
      out.write("\t            <div class=\"col-xs-5 line\"><hr></div>\r\n");
      out.write("\t            \r\n");
      out.write("\t            <!-- Sliding div register -->\r\n");
      out.write("\t           \r\n");
      out.write("\t\t\t\t<div id=\"slider_register\" style=\"right:-342px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"sidebar_register\" onclick=\"open_panel_register()\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-plus-sign\">\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"headerRegister\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Register !</h3>\r\n");
      out.write("\t\t\t\t\t\t<form id=\"login-form\" action=\"register\" method=\"post\">\r\n");
      out.write("\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"email\">Email :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name =\"email\" placeholder=\"Enter email\" >\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"username\">Username :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name =\"username\" placeholder=\"Enter name\" >\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"pwd\">Password :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"pwd\" name =\"password\" placeholder=\"Enter password\">\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t    <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("\t\t\t\t\t  \t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t            <!-- Sliding div login-->\r\n");
      out.write("\t\t\t\t<div id=\"slider_login\" style=\"right:-342px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"sidebar_login\" onclick=\"open_panel_login()\"><i class=\"fa fa-sign-in\" ></i></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"headerLogin\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Sign up ! </h3>\r\n");
      out.write("\t\t\t\t\t\t<form id=\"login-form\" action=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t\t            <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"username\">Username :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name =\"username\" placeholder=\"Enter name\" >\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"pwd\">Password :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"pwd\" name =\"password\" placeholder=\"Enter password\">\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t    <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("\t\t\t\t\t  \t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t<a href =\"logout\" id =\"logout\"><i class=\"material-icons\">power_settings_new</i></a>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"full-bg\" style=\"background-image: url(Images/bg1.jpg)\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<section class=\"timeline\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1833</time>  \r\n");
      out.write("\t\t\t\t        \t<img src=\"Images/Alfred_Nobel/Alfred_Nobel_1.jpg\" alt=\"Alfred Nobel\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Alfred_Nobel.html\" class=\"btn btn-primary\">Read More</a>     \r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1903</time> \r\n");
      out.write("\t\t\t\t        \t<img src=\"Images/Marie_Curie/Marie_Curie.jpg\" alt=\"Marie Curie\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Marie_Curie.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1921</time> \r\n");
      out.write("\t\t\t\t        \t<img src=\"Images/Albert_Einstein/Einstein.jpeg\" alt=\"Albert Einstein\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Albert_Einstein.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1932</time> \r\n");
      out.write("\t\t\t\t      \t\t<img src=\"Images/Werner_Heisenberg/Werner_Heisenberg.jpg\" alt=\"Werner Heisenberg\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Werner_Heisenberg.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1962</time> \r\n");
      out.write("\t\t\t\t    \t\t<img src=\"Images/Linus_Pauling/Linus_Pauling.jpg\" alt=\"Linus Pauling\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Linus_Pauling.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1964</time> \r\n");
      out.write("\t\t\t\t        \t<img src=\"Images/Jean_Paul_Sartre/Jean_Paul_Sartre.jpg\" alt=\"Jean Paul Sartre\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t        \t\t<a href =\"Content/Jean_Paul_Sartre.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1964</time> \r\n");
      out.write("\t\t\t\t        \t<img src=\"Images/Martin_Luther_King/Martin_Luther_King.jpg\" alt=\"Martin Luther King\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Martin_Luther_King.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1979</time> \r\n");
      out.write("\t\t\t\t    \t\t<img src=\"Images/Mother_Teresa/Mother_Teresa.jpg\" alt=\"Mother Teresa\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Mother_Teresa.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t  \t\t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1989</time> \r\n");
      out.write("\t\t\t\t    \t\t<img src=\"Images/Tenzin_Gyatso/Tenzin_Gyatso.jpg\" alt=\"Tenzin Gyatso\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Tenzin_Gyatso.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \t<li>\r\n");
      out.write("\t\t\t\t    \t<div>\r\n");
      out.write("\t\t\t\t      \t\t<time>1993</time> \r\n");
      out.write("\t\t\t\t    \t\t<img src=\"Images/Nelson_Mandela/Nelson_Mandela.jpeg\" alt=\"Nelson Mandela\">\r\n");
      out.write("\t\t\t\t        \t<br />\r\n");
      out.write("\t\t\t\t        \t<a href =\"Content/Nelson_Mandela.html\" class=\"btn btn-primary\">Read More</a>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t  \t</li>\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t    </div> \r\n");
      out.write("\t\r\n");
      out.write("\t    <footer class=\"footer-basic-centered\">\r\n");
      out.write("\t\t\t<p class=\"footer-company-motto\">Timeline nobel prizes.</p>\r\n");
      out.write("\t\t\t<p class=\"footer-links\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">Home</a>\r\n");
      out.write("\t\t\t    ·\r\n");
      out.write("\t\t\t  \t<a href=\"#\">Contact</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p class=\"footer-company-name\">Colin Frapper &copy; 2017</p>\r\n");
      out.write("\t\r\n");
      out.write("\t    </footer>\r\n");
      out.write("\t    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("\t    <script src=\"Js/main.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t        \r\n");
      out.write("\t    <script>\r\n");
      out.write("\t    /**\r\n");
      out.write("\t \t\t@role : open the register panel\r\n");
      out.write("\t    **/\r\n");
      out.write("\t    function open_panel_register() \r\n");
      out.write("\t    {\r\n");
      out.write("\t\t    slideItRegister();\r\n");
      out.write("\t\t    var a = document.getElementById(\"sidebar_register\");\r\n");
      out.write("\t\t    a.setAttribute(\"id\", \"sidebar1Register\");\r\n");
      out.write("\t\t    a.setAttribute(\"onclick\", \"close_panel_register()\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    /**\r\n");
      out.write("\t    \t@role : open the login panel \r\n");
      out.write("\t    **/\r\n");
      out.write("\t    function open_panel_login() \r\n");
      out.write("\t    {\r\n");
      out.write("\t\t\tslideItLogin();\r\n");
      out.write("\t\t\tvar a = document.getElementById(\"sidebar_login\");\r\n");
      out.write("\t\t\ta.setAttribute(\"id\", \"sidebar1Login\");\r\n");
      out.write("\t\t\ta.setAttribute(\"onclick\", \"close_panel_login()\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    /**\r\n");
      out.write("\t\t\t@role : slide the register bar\r\n");
      out.write("\t\t**/\r\n");
      out.write("\t    function slideItRegister() \r\n");
      out.write("\t    {\r\n");
      out.write("\t\t    var slidingDiv = document.getElementById(\"slider_register\");\r\n");
      out.write("\t\t    var stopPosition = 0;\r\n");
      out.write("\t\t    if (parseInt(slidingDiv.style.right) < stopPosition) \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t    slidingDiv.style.right = parseInt(slidingDiv.style.right) + 2 + \"px\";\r\n");
      out.write("\t\t\t    setTimeout(slideItRegister, 1);\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    /**\r\n");
      out.write("\t\t\t@role : slide the login bar\r\n");
      out.write("\t\t**/\r\n");
      out.write("\t\r\n");
      out.write("\t    function slideItLogin() \r\n");
      out.write("\t    {\r\n");
      out.write("\t        var slidingDiv = document.getElementById(\"slider_login\");\r\n");
      out.write("\t        var stopPosition = 0;\r\n");
      out.write("\t        if (parseInt(slidingDiv.style.right) < stopPosition) \r\n");
      out.write("\t        {\r\n");
      out.write("\t\t        slidingDiv.style.right = parseInt(slidingDiv.style.right) + 2 + \"px\";\r\n");
      out.write("\t\t        setTimeout(slideItLogin, 1);\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    \r\n");
      out.write("\t    /**\r\n");
      out.write("\t\t\t@role : close the register bar\r\n");
      out.write("\t\t**/\r\n");
      out.write("\t    function close_panel_register() \r\n");
      out.write("\t    {\r\n");
      out.write("\t\t    slideInRegister();\r\n");
      out.write("\t\t    a = document.getElementById(\"sidebar1Register\");\r\n");
      out.write("\t\t    a.setAttribute(\"id\", \"sidebar_register\");\r\n");
      out.write("\t\t    a.setAttribute(\"onclick\", \"open_panel_register()\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    \r\n");
      out.write("\t    /**\r\n");
      out.write("\t\t\t@role : close the login bar\r\n");
      out.write("\t\t**/\r\n");
      out.write("\t    function close_panel_login() \r\n");
      out.write("\t    {\r\n");
      out.write("\t        slideInLogin();\r\n");
      out.write("\t        a = document.getElementById(\"sidebar1Login\");\r\n");
      out.write("\t        a.setAttribute(\"id\", \"sidebar_login\");\r\n");
      out.write("\t        a.setAttribute(\"onclick\", \"open_panel_login()\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    \r\n");
      out.write("\t    /**\r\n");
      out.write("\t\t\t@role : slide in the register bar\r\n");
      out.write("\t\t**/\r\n");
      out.write("\t    function slideInRegister() \r\n");
      out.write("\t    {\r\n");
      out.write("\t\t    var slidingDiv = document.getElementById(\"slider_register\");\r\n");
      out.write("\t\t    var stopPosition = -342;\r\n");
      out.write("\t\t    if (parseInt(slidingDiv.style.right) > stopPosition) \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t    slidingDiv.style.right = parseInt(slidingDiv.style.right) - 2 + \"px\";\r\n");
      out.write("\t\t\t    setTimeout(slideInRegister, 1);\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    /**\r\n");
      out.write("\t\t\t@role : slide in the login bar\r\n");
      out.write("\t\t**/\r\n");
      out.write("\t    function slideInLogin() \r\n");
      out.write("\t    {\r\n");
      out.write("\t        var slidingDiv = document.getElementById(\"slider_login\");\r\n");
      out.write("\t        var stopPosition = -342;\r\n");
      out.write("\t        if (parseInt(slidingDiv.style.right) > stopPosition) \r\n");
      out.write("\t        {\r\n");
      out.write("\t\t        slidingDiv.style.right = parseInt(slidingDiv.style.right) - 2 + \"px\";\r\n");
      out.write("\t\t        setTimeout(slideInLogin, 1);\r\n");
      out.write("\t        }\r\n");
      out.write("\t     }\r\n");
      out.write("\t    \r\n");
      out.write("\t    </script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
